name: Sync Git Folder

concurrency: prod_environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Update git folder
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Update git folder
        run: databricks repos update /Workspace/Users/marcus.egelund-muller@devoteam.com/databricks-stocks --branch main
      - name: Validate bundle
        run: databricks bundle validate
      - name: Deploy bundle
        run: databricks bundle deploy
